version: 0.2

phases:
  install:
    commands:
      - echo Restoring NuGet packages
      - nuget restore .\FBZapp.sln

  build:
    commands:
      - echo Building and packaging MVC web application
      - msbuild .\FBZapp.Mvc\FBZapp.Mvc.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=false
      - echo Listing packaged MVC files
      - Get-ChildItem .\FBZapp.Mvc\obj\Release\Package\PackageTmp -Recurse
      - echo Build and package completed successfully

artifacts:
  base-directory: FBZapp.Mvc/obj/Release/Package/PackageTmp
  files:
    - '**/*'
